### ISSUE TITLE
FRDM-KW24D512 un-responsive after Bricking in Windows10

### ISSUE THREAD

**Issue by sgrmtb** [ARMmbed/DAPLink#578]
Board:
      - FRDM-KW24D512
Problem:
      - Out of my four above types of boards, three became unresponsive due to bricking in Windows 10 or while trying to unbrick the bricked ones.or
Condition:
      - When Powering through the OpenLink USB No LED Glows or blinks
      - No drive appears in the Windows (while keeping the reset button pressed or otherwise)
      - When powering through the KW24 USB Two RED LED's Glow
What did I Try:
      - Followed the steps mentioned in DAPLink bootloader update | Mbed  regarding the problem and possible solutions using External Debug Probe (ULINK Pro).
      - Downloaded the DPLink Source from DAPLink/DEVELOPERS-GUIDE.md at master · ARMmbed/DAPLink · GitHub and compiled the solution as per the given instructions correctly for the k20dx_frdmkw24d_if as the board used OpenSDA MCY named K20DX128Vxx5. 
      - I used the following settings for the Options for the Target:
<img width="631" alt="screenshot" src="https://user-images.githubusercontent.com/44848839/52236710-94c7e800-28ed-11e9-81b7-76e09d363e53.png">
<img width="629" alt="screenshot1" src="https://user-images.githubusercontent.com/44848839/52236821-e7a19f80-28ed-11e9-86ce-6fd98e80d461.png">
<img width="631" alt="screenshot2" src="https://user-images.githubusercontent.com/44848839/52236851-00aa5080-28ee-11e9-81ef-9f7630a09add.png">

- The uVision solution compiled correctly without any error, see the Build Window below:

<img width="524" alt="screenshot4" src="https://user-images.githubusercontent.com/44848839/52236885-16b81100-28ee-11e9-8689-8c0bbb9e035a.png">

- I Flashed the Program, It again worked without any error. See the Build Window Below.

<img width="773" alt="screenshot5" src="https://user-images.githubusercontent.com/44848839/52236895-1e77b580-28ee-11e9-8a88-0ed24180831f.png">

However, the Board did not come out of the Bricking State. THE SAME Problem Persists.

What NEXT?

**Comment by brianesquilona** [comment]
@sgrmtb, you can also update the bootloader by compiling k20dx_bl, then flash it like you did from uvision, then try if you can get into the bootloader mode, then flash the interface software.

**Comment by sgrmtb** [comment]
Hi, Brain,

Thanks for the concern, I will just try that. 

I have also tried another solution which also did not work.

What did I Try as the second method:
 
A. Copied the Bootloader from the Working Board using ULINK Pro into a Hex File.
   - Created a uVision Project with the K20DX128Vxx5.        
Used Save Command as follows to Read the Bootloader into a Hex FIle
SAVE MyFile.hex 0X0, 0X0001FFFF 
The hex file was created successfully in the project folder.
 
B. Flashed the Bricked boards with the copied Hex File.
   - Generate a uVision project
   - Select ULINKpro as debug interface
-   Entered the hex file name into 'Name of Executable' in the dialog 'Options for Target - Output'    
   - Performed a Flash download.
 
It showed that the programme has been flashed successfully, but
 
 
Same Problem Flashing Successful but the Boards not Working. AM I using the addresses correctly?

Meanwhile I will try with your solution.

Regards
Dr. M. Tariq Banday

e-mail:  sgrmtb@yahoo.com <mailto:sgrmtb@yahoo.com> (p), sgrmtb@gmail.com <mailto:sgrmtb@gmail.com> (a)
Url: http://banday.in <http://banday.in/>, Skype: tariq.banday

**Comment by brianesquilona** [comment]
@sgrmtb the strange thing is that bootloader or MAINTENANCE mode/drive should be working (when you push the reset button and reconnect the usb). All the addresses you want to know is in daplink_addr.h.

You might also try Erase sector setting instead of erasing the whole chip.

**Comment by sgrmtb** [comment]
Dear Brain,
	
	Thank You. It worked fine. I was able to get the board out of the bricking state. Thanks.

	I am still wondering why did the other solution not work.

	Further, I still have some problem with the debugging using ULINK Pro and flashing the program through ULINK Pro using uVision. 

	I have exported a program from the mBed and it compiles well in Keil. How should I flash into the main controller using ULINK Pro, so that I can use ULINK Pro as debugger.

Best Wishes

Dr. M. Tariq Banday
Head, Department of Electronics and Inst. Technology
University of Kashmir, Srinagar, 190006, J&K
Tel/Fax: +91 194 2415542 (direct) 
Tel: +91 194 2272381, Mob: +91 9419548922
e-mail:  sgrmtb@yahoo.com <mailto:sgrmtb@yahoo.com> (p), sgrmtb@gmail.com <mailto:sgrmtb@gmail.com> (a)
Url: http://banday.in <http://banday.in/>, Skype: tariq.banday

**Comment by sgrmtb** [comment]
Yes, it is right. I am able to debug using USB. I want to debug and program using ULINK Pro.

The board details are here:




https://www.nxp.com/docs/en/user-guide/FRDMKW24DUG.pdf <https://www.nxp.com/docs/en/user-guide/FRDMKW24DUG.pdf>


Do I have to connect my 10 pin cortex header to KW24SWD>

Best Wishes

Dr. M. Tariq Banday

e-mail:  sgrmtb@yahoo.com <mailto:sgrmtb@yahoo.com> (p), sgrmtb@gmail.com <mailto:sgrmtb@gmail.com> (a)
Url: http://banday.in <http://banday.in/>, Skype: tariq.banday

**Comment by brianesquilona** [comment]
Yes, you already have the KW24 SWD pins exposed, just connect to this instead of the OpenLink Debug pins.

**Comment by sgrmtb** [comment]
Yes, I did that, I am able to do it now.

I can also program it through this header?

Dr. M. Tariq Banday

e-mail:  sgrmtb@yahoo.com <mailto:sgrmtb@yahoo.com> (p), sgrmtb@gmail.com <mailto:sgrmtb@gmail.com> (a)
Url: http://banday.in <http://banday.in/>, Skype: tariq.banday

**Comment by brianesquilona** [comment]
Yep, certainly. :)

**Comment by sgrmtb** [comment]
Yes. Thanks.

With the same Board, Can I,

-  use ARM ULINK Plus for Energy Analysis in the similar manner or I have to cut some circuit?

-  use ARM ULINK Pro  and ULINK Plus in Kinetics Design Studio as well?

Dr. M. Tariq Banday

e-mail:  sgrmtb@yahoo.com <mailto:sgrmtb@yahoo.com> (p), sgrmtb@gmail.com <mailto:sgrmtb@gmail.com> (a)
Url: http://banday.in <http://banday.in/>, Skype: tariq.banday
